// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo34dsqnUr695Kp958tYmazYSFfXV2o-c',
    appId: '1:481626368925:android:60b1fbd26a5814da105d74',
    messagingSenderId: '481626368925',
    projectId: 'tobeto-mobile-app-527b7',
    storageBucket: 'tobeto-mobile-app-527b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqMcXYZvx9VUkzBz0AzWpl-TjiEo9PbTs',
    appId: '1:481626368925:ios:c0b0182f966ebfe7105d74',
    messagingSenderId: '481626368925',
    projectId: 'tobeto-mobile-app-527b7',
    storageBucket: 'tobeto-mobile-app-527b7.appspot.com',
    iosClientId: '481626368925-1nclssse0dcenju97et5o46bm68fv0l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobetoMobileApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRkXd24ldqs5_16zRhlJvfLO-xN4EAyY',
    appId: '1:481626368925:web:62176422f878e07f105d74',
    messagingSenderId: '481626368925',
    projectId: 'tobeto-mobile-app-527b7',
    authDomain: 'tobeto-mobile-app-527b7.firebaseapp.com',
    storageBucket: 'tobeto-mobile-app-527b7.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqMcXYZvx9VUkzBz0AzWpl-TjiEo9PbTs',
    appId: '1:481626368925:ios:c0b0182f966ebfe7105d74',
    messagingSenderId: '481626368925',
    projectId: 'tobeto-mobile-app-527b7',
    storageBucket: 'tobeto-mobile-app-527b7.appspot.com',
    iosClientId: '481626368925-1nclssse0dcenju97et5o46bm68fv0l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobetoMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIRkXd24ldqs5_16zRhlJvfLO-xN4EAyY',
    appId: '1:481626368925:web:673fa984ddc9b32a105d74',
    messagingSenderId: '481626368925',
    projectId: 'tobeto-mobile-app-527b7',
    authDomain: 'tobeto-mobile-app-527b7.firebaseapp.com',
    storageBucket: 'tobeto-mobile-app-527b7.appspot.com',
  );

}